### PR TITLE
Renamed gem

### PR DESCRIPTION
**Pull request by jamtur01**
Replaced use of master/slave language with leader/replica.

### CODE REVIEW

**Comment by selftext** [comment]
:clap:

**Comment by samuelcole** [comment]
@dandrabik @dandrabik @dandrabik

**Comment by jamtur01** [comment]
@samuelcole That @dandrabik is currently deep in the wilds of South America.

**Comment by cainlevy** [comment]
:100: 

i'll rebase my pull request after!

**Comment by ktheory** [comment]
Style!

replicants

**Pull request merged**
